# Generated by Django 2.2.1 on 2019-06-03 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 11, 53, 8, 304529), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='notelist',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 11, 53, 8, 305530), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='notepicture',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 11, 53, 8, 305530), verbose_name='date published'),
        ),
    ]
